// products
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_UPDATE = "PRODUCT_LIST_UPDATE";
export const PRODUCT_LIST_END_UPDATE = "PRODUCT_LIST_END_UPDATE";
export const PRODUCT_LIST_START_UPDATE = "PRODUCT_LIST_START_UPDATE";
export const PRODUCT_LIST_FILTER = "PRODUCT_LIST_FILTER";
